### ISSUE TITLE
Not able to see ContosoInsurance Dataase in SQLVM's

### ISSUE THREAD

**Issue by anushabc** [microsoft/MCW-Building-a-resilient-IaaS-architecture#103]
In Exercise 1 Task 2 step 32 Contoso insurance database is not showing up. We have checked in all the 3 SQLVM's the result is same no contoso insurance database.

![image](https://user-images.githubusercontent.com/66515706/175364659-01c2cd8a-4869-4ecc-9a60-cff60718710f.png)

We were able to see the database in yesterdays deployment, we started facing issue after latest updates, not sure if it's affecting something

**Comment by anushabc** [comment]
@DawnmarieDesJardins  can you please help us get this fixed as we have a lab schedule on 28th.

**Comment by SumitMalik51** [comment]
Hi, Just FYI, we see that the Database is not getting downloaded in D dir. 
![image](https://user-images.githubusercontent.com/45102602/175366001-cac7ae9c-36ad-4dde-ae7c-1e52956d4fcb.png)

**Comment by DawnmarieDesJardins** [comment]
@anushabc @SumitMalik51 - Is this possibly tied to issue #101 that Ben put through a fix for a couple of hours ago?  I want to make sure you're looking at the most current version.  Thanks!

**Comment by SumitMalik51** [comment]
Hi @DawnmarieDesJardins , Yeah we check and that workaround fixed that issue, however this issue is in the new environment only where the latest changes are pulled and used. The previous one was while connecting to the SQLVm but here the DB is not available in SQVM
Thanks

**Comment by benstegink** [comment]
@SumitMalik51 this issue was fixed as a part of issue #101 , you just need to run the BHOL Task 2 with the latest changes from a few hours ago.

**Comment by SumitMalik51** [comment]
hi @benstegink , we have checked in a few environments, and in some its working fine but in some, the DB is not there or is in restoring stage

**Comment by DawnmarieDesJardins** [comment]
@anushabc and @SumitMalik51 - Hello!  Checking in to see if you have an update for us from the comments above.  Thanks.

**Comment by SumitMalik51** [comment]
Hi @benstegink , we are using US locations only and not changing size and other details. However the 28th lab delivery is canceled due to some other issue, so will be testing it again next week to check on this. 

Thanks for the workaround.

**Comment by timahenning** [comment]
Hi @SumitMalik51,  just checking in on the testing.

**Comment by DawnmarieDesJardins** [comment]
Closing issue.  Please reopen as needed.
