### ISSUE TITLE
Exercise 2 Task 1 Step 10 and related steps should be updated

### ISSUE THREAD

**Issue by GokhanSenyuz** [microsoft/MCW-Building-a-resilient-IaaS-architecture#107]
Run as accounts does not available anymore.

**Azure Automation Run As Account will retire on 30 September 2023 and will be replaced with Managed Identities. Before 30 September 2023, you need to start migrating your runbooks to use managed identities. Moreover, starting 1 April 2023, creation of new Run As accounts would not be possible. For more information, see [migrating from an existing Run As accounts to managed identity.](https://aka.ms/migrate-run-as-accounts-managed-identity)**

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of #108
