### ISSUE TITLE
Availability Zones to be included in the workshop

### ISSUE THREAD

**Issue by bendq** [Microsoft/MCW-Building-a-resilient-IaaS-architecture#17]
Availability zones went GA six months ago and are a way to achieve 99.99% SLAs on VMs  https://azure.microsoft.com/en-au/global-infrastructure/availability-zones/

AZ are currently available in a number of regions and being expanded to more as a priority. This is a feature that our competition has in some locations and leverage strongly. 

I'd like to see us use a combination of AZ + current sceanrios (load balancers, replication etc) to address this

**Comment by mwasham** [comment]
AV Zones are now in - we have them in the West US 2 sub. 
https://github.com/Microsoft/MCW-Building-a-resilient-IaaS-architecture/tree/nov-2018-updates
