### ISSUE TITLE
WDS - trainer presentation

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Building-a-resilient-IaaS-architecture#2]
Entire PPT - Please correct punctuation.  Remove periods at the end of single sentences that are bulleted items (unless it is a question mark).
Slide 2 - Abstract in PPT does not match WDS abstract
Slide 10 - Availability aet??  AET instead?  When using an acronym, you need to spell it out the first time please. 
Slide 13 - Customer objection, 2nd bullet.  Capitalize That (2nd sentence)
Slide 14 - 2nd bullet... ADDS DSs? Need to spell out an acronym the first time you use it
Slide 15 - Images need to be flat and alt-text updated - accessibility readers can read the multiples.
Slide 21 - Alt-text missing
Slide 22 - Correct title (random s at the end).  Missing alt-text.  Cannot use red image with white text that small, it will not pass accessibility test.
Slide 23 - Same as above
Slide 24 - Missing alt-text
Slide 25 - Missing alt-text
Slide 26 - Read on white is hard to read, not sure it will pass accessibility standards.  Can you change to dark blue?
Slide 29 - 3rd bullet, correct punctuation.  ….VPN Gateway and other network health, (add comma)
Slide 30 - Correct punctuation in answer section please

**Comment by DawnmarieDesJardins** [comment]
Reopening issue: Corrections to slides 13 & 21 (alt-text) missed.

**Comment by mwasham** [comment]
updated
