### ISSUE TITLE
Broken Images

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Building-a-resilient-IaaS-architecture#25]
Hi Michael,
I worked through the field PR but can't get the two images to show up correctly in the trainer guide.
Please take a look:
Line 584
Line 633 - this one is also missing an alt-text

**Comment by Jeff-Opsgility** [comment]
Paul is still working on the issue, will have it resolved as quickly as we can.

**Comment by paulopsgility** [comment]
This is resolved.

**Comment by DawnmarieDesJardins** [comment]
Closing issue.  Images fixed, HTML files updated.
Thanks Paul!!
