### ISSUE TITLE
March 2019 - Scheduled content update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Building-a-resilient-IaaS-architecture#28]
@mwasham @Jeff-Opsgility 
Opsgility team - 
This workshop is scheduled for an update.  Please update this issue with suggested content changes.  Once done, we will assign to our SME team for review and additional feedback.

**Comment by paulopsgility** [comment]
Propose mirroring the recent changes to the WDS:

- Test/fix, screenshot updates 
- Replace scale sets with VMs (to support ASR and to mirror the WDS)
- Implement region to region Azure Site Recovery

**Comment by mapucket-msft** [comment]
Would updating the SQL AOAG design to use the Cloud Witness option be of interest?  https://blogs.msdn.microsoft.com/mihansen/2017/12/20/sql-server-2017-always-on-with-cloud-witness-azure-resource-manager-template/

**Comment by ChongRX78** [comment]
> Would updating the SQL AOAG design to use the Cloud Witness option be of interest?  https://blogs.msdn.microsoft.com/mihansen/2017/12/20/sql-server-2017-always-on-with-cloud-witness-azure-resource-manager-template/

@mapucket-msft - could you give a bit more context on the reason behind? For example is having Cloud Witness a more robust architecture? Is it a best practice?

**Comment by mapucket-msft** [comment]
@ChongRX78 - there's a couple of things that come to mind.  Removes another VM that requires patching, monitoring and complexity.  A VM witness becomes problematic when you need to reboot the witness, i.e. - manually disabling autofailover to prevent replica issues, etc..  Easier to template and deploy.  Less reliability issues when relying on Azure Storage rather than a VM.  Part of Windows Fail-over Cluster Services.  And costs less to operate a cluster.

**Comment by ChongRX78** [comment]
@mapucket-msft - thank you for the context and yes it makes great sense. @paulopsgility - would you be able to add this as well?

**Comment by mayurigupta13** [comment]
Over an above these updates, I think it would be a good idea to add an architecture diagram in the problem description. I found that a lot of teams had questions around the current networking setup.

**Comment by DawnmarieDesJardins** [comment]
Closing issue, resolved with March 2019 update merge.
