### ISSUE TITLE
Why Not Azure Virtual WAN?

### ISSUE THREAD

**Issue by gamullen** [Microsoft/MCW-Building-a-resilient-IaaS-architecture#31]
Any reason Azure Virtual WAN is not suggested to tie all the VPNs together redundantly? It would provide connectivity not only from each branch to Azure, but also between branches.

Too expensive?

Thanks, Gary

**Comment by DawnmarieDesJardins** [comment]
@gamullen 
Thanks Gary, sending a meeting request to you to get additional information.
Dawnmarie

**Comment by DawnmarieDesJardins** [comment]
Closing issue, addressed via meeting.
