### ISSUE TITLE
Issue in Exercise 2 Task 4, step 19 while running powershell command. 

### ISSUE THREAD

**Issue by Abhishekpathania01** [Microsoft/MCW-Building-a-resilient-IaaS-architecture#32]
[Ecercise 2 Task 4](https://github.com/Microsoft/MCW-Building-a-resilient-IaaS-architecture/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Building%20a%20resilient%20IaaS%20architecture.md#task-2-create-the-active-directory-deployment-in-the-second-azure-region), powershell command "Set-DnsServerPrimaryZone -Name contoso.com -DynamicUpdate NonsecureAndSecure"  is failing with error: The term  'Set-DnsServerPrimaryZone' is not recognized as the name of cmdlet, function , script file, or operable program. 

Could you please look into this and fix ASAP, you might need to update the custom script  extension which is using for ADVM.

Thanks,
Abhishek Pathania

**Comment by paulopsgility** [comment]
This should be fixed now. Looks like the DNS powershell cmdlets were no longer being installed as part of the management tools of the AD feature. I added an explicit install to fix it.
