### ISSUE TITLE
Exercise 5: Validate resiliency

### ISSUE THREAD

**Issue by GhumanNavneet** [Microsoft/MCW-Building-a-resilient-IaaS-architecture#33]
Task 3: Validate backups are taken
In Step 18, not able to run the command. showing following error:
Get-Process : A positional parameter cannot be found that accepts argument '.\deploy-cloudshop-db.ps1'.

Please mention in which virtual machine we need to run the command.

In Exercise 3: Build web tier and SQL for resiliency > Task 1: Deploy SQL Always-On Cluster > Step 5 , please mention from which virtual machine we can access SQL1 and SQL0 via RDP.

**Comment by GhumanNavneet** [comment]
any progress??

**Comment by DawnmarieDesJardins** [comment]
@mwasham @Jeff-Opsgility 
Please review and advise.

**Comment by ciphertxt** [comment]
@GhumanNavneet Just to clarify, you mean Exercise 3/Task 1/Step 18? It sounds like you didn't download the script from the repo at https://github.com/opsgility/cw-building-resilient-iaas-architecture/tree/master/script-extensions. You need to first download the script deploy-cloud-db.ps1 from that repo and then execute it. The script should be executed from SQL0 which you should have moved back to in step 15. 

For Exercise 3/Task 1/Step 5 you can access SQL0 and SQL1 from any other machine on the same VNET, such as DC01, DC02, DC03, or DC04 which all have public IP resources associated with them.

**Comment by GhumanNavneet** [comment]
okay. thanks.

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved.
