### ISSUE TITLE
SQL AOAG configuration is completely broken

### ISSUE THREAD

**Issue by pankaj1102** [microsoft/MCW-Building-a-resilient-IaaS-architecture#34]
SQL AlwaysOn Availability Configuration does not work with the existing steps. Multiple issues were detected.
1. AdventureWorks is restored with Simple recovery model.
2. Lab instructions go straight into AOAG dashboard without walking the attendee through configuration steps.
3. Step missing to create a fileshare
4. Steps missing to through the AOAG wizard

**Comment by DawnmarieDesJardins** [comment]
@mwasham @Jeff-Opsgility 
Please review/advise.

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility 
Removed Jeff, added Paul for visibility.  Please review/advise.

**Comment by paulopsgility** [comment]
1. Adventure Works is set to full recovery in a prior step, if it wasn't, the wizard would still flag it and require it to be set to full recovery. Either way would have the desired impact which is to emphasize that full recovery is required.
2. Ex 3, Task 1, Step 20 instructs student to step through the wizard. We can add the wizard steps back in for clarity.
3. Use automatic seeding, no file share required.
4. This is the same as 2 

We'll add the Availability Group Wizard steps in the June test/fix

**Comment by DawnmarieDesJardins** [comment]
Thanks @paulopsgility 
Labeling this issue as an enhancement to be addressed at the next workshop update.

**Comment by cassiejones444** [comment]
There doesn't seem to be any steps to configure the SQL listener for the load balancer for the SQL cluster.

Specifically these type steps:

https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sql/virtual-machines-windows-portal-sql-availability-group-tutorial#configure-listener

Without which I'm not sure how the web front end is failing over automatically.

Thanks
Cassie

**Comment by cassiejones444** [comment]
And the PowerShell to correctly configure the ILB is now in the Wizard?

If so that is a welcome step forward.

Thanks
Cassie

Cassandra Jones CISSP
Cloud Solution Architect
Azure Applications & Infrastructure
Customer Success Unit

M: +61 409 797 294
E:  Cassandra.jones@microsoft.com<mailto:Cassandra.jones@microsoft.com>

Office: 1 Epping Road, North Ryde, NSW 2113

[Microsoft Logo]

**Comment by jtuliani** [comment]
Fixed in #41

**Comment by paulopsgility** [comment]
Resolved in latest update
