### ISSUE TITLE
Resilient Web tier deployment failed

### ISSUE THREAD

**Issue by pankaj1102** [microsoft/MCW-Building-a-resilient-IaaS-architecture#35]
Deploying the Web Tier resilient architecture failed with the following error in deployment:

{ "id": "/subscriptions/5903ed1d-9bce-4fe0-8226-ec87c9d595c2/resourceGroups/ResilientIaaSRG/providers/Microsoft.Resources/deployments/Microsoft.Template/operations/EFE52F28DDB27204", "operationId": "EFE52F28DDB27204", "properties": { "provisioningOperation": "Create", "provisioningState": "Failed", "timestamp": "2019-05-08T01:31:45.0444165Z", "duration": "PT1.3043664S", "trackingId": "30348c7f-7c28-45f0-9b10-45021a56943a", "serviceRequestId": "7614d23e-001f-4829-837b-98cca362de9a", "statusCode": "BadRequest", "statusMessage": { "error": { "code": "InvalidResourceReference", "message": "Resource /subscriptions/5903ed1d-9bce-4fe0-8226-ec87c9d595c2/resourceGroups/ResilientIaaSRG/providers/Microsoft.Network/virtualNetworks/VNET1/subnets/App referenced by resource /subscriptions/5903ed1d-9bce-4fe0-8226-ec87c9d595c2/resourceGroups/ResilientIaaSRG/providers/Microsoft.Network/networkInterfaces/WebVM-2NetworkInterface was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.", "details": [] } }, "targetResource": { "id": "/subscriptions/5903ed1d-9bce-4fe0-8226-ec87c9d595c2/resourceGroups/ResilientIaaSRG/providers/Microsoft.Network/networkInterfaces/WebVM-2NetworkInterface", "resourceType": "Microsoft.Network/networkInterfaces", "resourceName": "WebVM-2NetworkInterface" }, "request": { "content": { "location": "australiaeast", "tags": { "displayName": "WebVM-2Nic" }, "properties": { "ipConfigurations": [ { "name": "ipconfig1", "properties": { "privateIPAllocationMethod": "Dynamic", "subnet": { "id": "/subscriptions/5903ed1d-9bce-4fe0-8226-ec87c9d595c2/resourceGroups/ResilientIaaSRG/providers/Microsoft.Network/virtualNetworks/VNET1/subnets/App" }, "loadBalancerBackendAddressPools": [ { "id": "/subscriptions/5903ed1d-9bce-4fe0-8226-ec87c9d595c2/resourceGroups/ResilientIaaSRG/providers/Microsoft.Network/loadBalancers/OPSLB/backendAddressPools/BackendPool1" } ], "publicIPAddress": { "id": "/subscriptions/5903ed1d-9bce-4fe0-8226-ec87c9d595c2/resourceGroups/ResilientIaaSRG/providers/Microsoft.Network/publicIPAddresses/webip2" } } } ] } } }, "response": { "content": { "error": { "code": "InvalidResourceReference", "message": "Resource /subscriptions/5903ed1d-9bce-4fe0-8226-ec87c9d595c2/resourceGroups/ResilientIaaSRG/providers/Microsoft.Network/virtualNetworks/VNET1/subnets/App referenced by resource /subscriptions/5903ed1d-9bce-4fe0-8226-ec87c9d595c2/resourceGroups/ResilientIaaSRG/providers/Microsoft.Network/networkInterfaces/WebVM-2NetworkInterface was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.", "details": [] } } } }}

There's no additional instructions in Task 2 Exercise 3 to validate and review the deployment in order to understand the Scale Set configuration and why its better than a VM without scale set.

**Comment by DawnmarieDesJardins** [comment]
@mwasham @Jeff-Opsgility 
Please review/advise.

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility 
Hi Paul, 
Please review/advise.
Thanks, Dawnmarie

**Comment by paulopsgility** [comment]
Based on the error you posted, it looks like you deployed to a different region than your vnet. We'll add some instructions to specify the region here. 

Note that you are not deploying to the regions defined in the lab guide (East US2 and Central US). That is fine, but you do have to do the mental acrobatics to keep those regions sorted out if you choose to go that route.

**Comment by DawnmarieDesJardins** [comment]
Thanks @paulopsgility 
@pankaj1102 - Please advise if this has answered your questions and we can close the issue as resolved.
Thanks, Dawnmarie

**Comment by DawnmarieDesJardins** [comment]
Closing issue.  @pankaj1102 please reopen issue if necessary.
