### ISSUE TITLE
Issue in Exercise 5 again

### ISSUE THREAD

**Issue by GhumanNavneet** [microsoft/MCW-Building-a-resilient-IaaS-architecture#37]
Getting error while executing the PowerShell command for deploying the cloudshop database, even after downloading and running deploy-cloudshop-db.ps1 file from give link. Below I have mention the error can please specify necessary steps for more clarification :

.\deploy-cloudshop-db.ps1 : The term '.\deploy-cloudshop-db.ps1' is not recognized as the name of a cmdlet, 
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that 
the path is correct and try again.
At line:1 char:1
+ .\deploy-cloudshop-db.ps1 -user "demouser" -password "demo@pass123" - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\deploy-cloudshop-db.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by DawnmarieDesJardins** [comment]
@GhumanNavneet 
Hello!  Please let us know if this issue is solved and we can close.
Thanks, Dawnmarie

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved.  @GhumanNavneet please reopen if needed.
Dawnmarie
