### ISSUE TITLE
Active Directory Domain Controller Solution

### ISSUE THREAD

**Issue by cassiejones444** [microsoft/MCW-Building-a-resilient-IaaS-architecture#40]
The preferred solution for the training guide has only one DC in the West US region:

West US 2: 172.16.0.0/16 (Domain Controller: 172.16.2.4)

And yet the AD configuration guide calls out two DCs in both the Azure Regions.

Suggest the DC IP address list is updated.

**Comment by jtuliani** [comment]
Adding missing IP in Sept '19 update. Also fixed NSG tables that used '....3.0' instead of '....2.0' for the identity address spaces.

**Comment by jtuliani** [comment]
Fixed in #41

**Comment by paulopsgility** [comment]
Resolved in last update
