### ISSUE TITLE
Error while testing lab

### ISSUE THREAD

**Issue by GhumanNavneet** [microsoft/MCW-Building-a-resilient-IaaS-architecture#42]
Getting below error while deploying SQL and Web VMs:

SQL VMs deployment error:
b7bb-9e2552b9da15", "statusCode": "Conflict", "statusMessage": { "status": "Failed", "error": { "code": "ResourceDeploymentFailure", "message": "The resource operation completed with terminal provisioning state 'Failed'.", "details": [ { "code": "VMExtensionProvisioningError", "message": "VM has reported a failure when processing extension 'joindomain'. Error message: \"Join failed for Domain 'contoso.com' with the error: The process cannot access the file 'C:\\WindowsAzure\\Logs\\Plugins\\Microsoft.Compute.JsonADDomainExtension\\1.3.2\\ADDomainExtension.log' because it is being used by another process.\"." } ] } }, "targetResource": { "id": "/subscriptions/5c513ec3-4392-4ceb-8b89-f504636afc65/resourceGroups/CloudShopRG/providers/Microsoft.Compute/virtualMachines/SQL0/extensions/joindomain", "resourceType": "Microsoft.Compute/virtualMachines/extensions", "resourceName": "SQ
+-L0/joindomain" } }}	

Web VMs deployment error:
{ "id": "/subscriptions/5c513ec3-4392-4ceb-8b89-f504636afc65/resourceGroups/CloudShopRG/providers/Microsoft.Resources/deployments/Microsoft.Template_1/operations/64E72D95B5D44753", "operationId": "64E72D95B5D44753", "properties": { "provisioningOperation": "Create", "provisioningState": "Failed", "timestamp": "2019-11-15T10:18:51.7679589Z", "duration": "PT18M9.6074955S", "trackingId": "b8ed335b-5e85-4fe3-862a-35f6ebe5f1c8", "statusCode": "Conflict", "statusMessage": { "status": "Failed", "error": { "code": "ResourceDeploymentFailure", "message": "The resource operation completed with terminal provisioning state 'Failed'.", "details": [ { "code": "VMExtensionProvisioningError", "message": "VM has reported a failure when processing extension 'joindomain'. Error message: \"Exception(s) occured while joining Domain 'contoso.com'\"." } ] } }, "targetResource": { "id": "/subscriptions/5c513ec3-4392-4ceb-8b89-f504636afc65/resourceGroups/CloudShopRG/providers/Microsoft.Compute/virtualMachines/WebVM-2/extensions/joindomain", "resourceType": "Microsoft.Compute/virtualMachines/extensions", "resourceName": "WebVM-2/joindomain" } }}

Also, all images need to be get updated.

**Comment by GhumanNavneet** [comment]
any update??

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility 
Paul, do you have an ETA for this?

**Comment by paulopsgility** [comment]
@GhumanNavneet We are looking into this. 

@ciphertxt Would you take a look at this? Might be due to the low memory issue Azure VMs have been hitting in recent months.

**Comment by GhumanNavneet** [comment]
any update on this

**Comment by ciphertxt** [comment]
@GhumanNavneet @paulopsgility Taking a look at this today

**Comment by ciphertxt** [comment]
@GhumanNavneet - We'll get this fixed in the [dec-2019](https://github.com/microsoft/MCW-Building-a-resilient-IaaS-architecture/tree/dec-2019-breakfix) update. 

For now, if you need to get the LabVM going, load the [template ](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fcloudworkshop.blob.core.windows.net%2Fbuilding-resilient-iaas-architecture%2Flab-resources%2FLabRG.json) and update the `imageVersion` variable to `latest` in the `variables` group of the template.

For the issue you noted above with domain join failures, I've been unable to replicate it after deploying the [CloudShop template](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fcloudworkshop.blob.core.windows.net%2Fbuilding-resilient-iaas-architecture%2Flab-resources%2Fcloudshop.json) several times. 

Can you provide further clarification on "Also, all images need to get updated"?

**Comment by DawnmarieDesJardins** [comment]
Closing issue with December test/fix merge.  @GhumanNavneet please let us know if you are still having trouble with the updated content.

**Comment by soheilkia** [comment]
I had an issue joining the domain controller VM from DR region to the DC in live region. I followed below steps below to address this issue. Credit goes to an article that i can't find anymore

Let's use nslookup to determine what SRV records are returned:

In a command prompt, type in the following and hit enter:
c:\>nslookup (hit enter)

Then type in the following and hit enter:
> _msdcs.yourdomain.com           (This should just show "_msdcs.yourdomain.com")

Then type in the following and hit enter:
> gc._msdcs.yourdomain.com        (This should show you the IP addresses of all of your GCs)
Then change the query type to SRV records with the next command:

> set q=srv

Now type in the following and hit enter:
> _ldap._tcp.dc._msdcs.yourdomain.com           (This test should show you your domain controllers)
Server:  dc-01.yourdomain.com
Address:  10.10.10.10

_ldap._tcp.dc._msdcs.yourdomain.com       SRV service location:
          priority       = 0
          weight         = 100
          port           = 389
          svr hostname   = dc-01.yourdomain.com
_ldap._tcp.dc._msdcs.yourdomain.com       SRV service location:
          priority       = 0
          weight         = 100
          port           = 389
          svr hostname   = dc-02.yourdomain.com
dc01.yourdomain.com  internet address = 10.10.10.10     
dc-02.yourdomain.com  internet address = 10.10.10.5      
>
