### ISSUE TITLE
Microsoft SQL Server Management Studio version

### ISSUE THREAD

**Issue by PrernaNagori09** [microsoft/MCW-Building-a-resilient-IaaS-architecture#45]
In this lab, we are using "Microsoft SQL Server Management Studio version 18" but in the lab guide "version 17" is mentioned. 
Excersice-3,Task-3 step-2

https://cloudworkshop.blob.core.windows.net/building-resilient-iaas-architecture/Hands-on%20lab/HOL%20step-by%20step%20-%20Building%20a%20resilient%20IaaS%20architecture.html#task-3-deploy-the-application-database-to-the-sql-always-on-cluster

![2020-01-08_16-00-12](https://user-images.githubusercontent.com/56402513/72049034-2735f000-32e4-11ea-9baf-6cab43357ebb.png)

**Comment by paulopsgility** [comment]
We'll update the lab guide at the next test/fix

**Comment by paulopsgility** [comment]
Resolved in latest test/fix
