### ISSUE TITLE
NSG-Web Tier

### ISSUE THREAD

**Issue by soheilkia** [microsoft/MCW-Building-a-resilient-IaaS-architecture#47]
This is not an issue, it's more of a question. 
First of all, i want to thank you all for sharing these materials. 
Is there any reason that there are no NSGs for Web Tier or even at Network interface? Isn't this best practice?
I will also be replacing load balancer with Application gateway + WAF2.

**Comment by paulopsgility** [comment]
@soheilkia thank's for the question. MCW's are built to run in roughly 4 hours (for the lab). This usually means that we have to take some liberties with certain areas of the lab which may not be the focus of the lab just to keep the time in check. For NSGs, I believe these are covered in more depth in the Enterprise Class Networking MCW.

The technology leads at Microsoft generally review and approve the labs and we do update them periodically. So if you want to submit this as an enhancement we can review it at the next update.

**Comment by DawnmarieDesJardins** [comment]
No response from original author, closing as resolved.
