### ISSUE TITLE
Issue: Not able to add file  (AddDC.ps1) form local file explorer to custom script extension.

### ISSUE THREAD

**Issue by PrernaNagori09** [microsoft/MCW-Building-a-resilient-IaaS-architecture#48]
**Exercise-2 Task-4(Format Data Disks and promote new VMs as additional Domain Controllers) Step-5: -**

**Hands-on Lab: -** User can't upload any file from our local system to custom script extension because the Azure Portal is updated as per the new updates, we have to use a storage account for uploading a file in the custom script extension. 

**Solution:-** In **before hands on lab** we need to provide a new storage account with the required files for custom script extension.

**Comment by paulopsgility** [comment]
We'll update all of the labs that use this as they go through test/fix/update

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #52
