### ISSUE TITLE
validation errors

### ISSUE THREAD

**Issue by pattasana** [microsoft/MCW-Building-a-resilient-IaaS-architecture#49]
Hi,

I've just started to Hands-on but i got error when deploy first template at before hands on section.

Error:
{"telemetryId":"70ccda62-1a48-4be2-bba7-e099250ef19a","bladeInstanceId":"Blade_b1cc6e0a4a074e3b8b1c5cbe1b7c8390_0_0","galleryItemId":"Microsoft.Template","createBlade":"DeployToAzure","code":"InvalidTemplateDeployment","message":"The template deployment 'Microsoft.Template' is not valid according to the validation procedure. The tracking id is 'd7613cc5-0658-4606-8eb2-5f12b6ba06bf'. See inner errors for details.","details":[{"code":"InvalidParameter","target":"imageReference","message":"The following list of images referenced from the deployment template are not found: Publisher: MicrosoftVisualStudio, Offer: visualstudio2019latest, Sku: vs-2019-comm-latest-ws2019, Version: 2019.12.02. Please refer to https://docs.microsoft.com/en-us/azure/virtual-machines/windows/cli-ps-findimage for instructions on finding available images."}]}

**Comment by paulopsgility** [comment]
@pattasana We are looking into this.

**Comment by cankarahaliloglu** [comment]
Hello @pattasana and @paulopsgility.

There is a wrong line in the template ("imageVersion" line 36) after I've you changed to image version number to "latest", it worked.

The wrong line;

>  36      "imageVersion": "2019.12.02",

Working;
 
> 36      "imageVersion": "latest",



Thanks

**Comment by paulopsgility** [comment]
@cankarahaliloglu  Updated the template. Should be working now.
