### ISSUE TITLE
deployment validation error

### ISSUE THREAD

**Issue by roie9876** [microsoft/MCW-Building-a-resilient-IaaS-architecture#50]
in "Before the hands-on lab setup guide" step:
Select the Deploy to Azure button below to open the Azure portal and launch the template deployment for the LabVM. Log in to the Azure portal using your subscription credentials if you are prompted to do so.
run this script:
https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fcloudworkshop.blob.core.windows.net%2Fbuilding-resilient-iaas-architecture%2Flab-resources%2FLabRG.json

get the following error:
{"telemetryId":"f6bc9ee7-7aaf-4ad6-be1d-892581c7adef","bladeInstanceId":"Blade_8b688088fac24df5aa101caad23ffe2c_0_0","galleryItemId":"Microsoft.Template","createBlade":"DeployToAzure","code":"InvalidTemplateDeployment","message":"The template deployment 'Microsoft.Template' is not valid according to the validation procedure. The tracking id is 'f8cd976a-dede-4c0d-854f-9a282727b068'. See inner errors for details.","details":[{"code":"InvalidParameter","target":"imageReference","message":"The following list of images referenced from the deployment template are not found: Publisher: MicrosoftVisualStudio, Offer: visualstudio2019latest, Sku: vs-2019-comm-latest-ws2019, Version: 2019.12.02. Please refer to https://docs.microsoft.com/en-us/azure/virtual-machines/windows/cli-ps-findimage for instructions on finding available images."}]}

**Comment by paulopsgility** [comment]
@roie9876 We already have an open issue on this one. I am closing as duplicate
