### ISSUE TITLE
June 2020 Update Suggestions

### ISSUE THREAD

**Issue by paulopsgility** [microsoft/MCW-Building-a-resilient-IaaS-architecture#51]
Here are our suggested updates for the June 2020 update. Please add any other suggestions or feedback to this issue.

- Remove the unmanaged disks dependency (managed disks have become the standard now) 
- Update to leverage ExpressRoute Global Reach
- Rebuild diagrams to use modern Azure icons
- Improve explanatory narrative
- Move data disk creation to the same the VM creation step
- Update SQL version to SQL Server 2019
- Increase VM size to avoid out of memory errors

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete with merge of PR #52
