### ISSUE TITLE
Issue on Step 14 of task 3

### ISSUE THREAD

**Issue by kevlopez69** [microsoft/MCW-Building-a-resilient-IaaS-architecture#53]
Attempted this lab in 2 different subscriptions, same error when getting to this step, tried it multiple times now, deleting and restarting all over. 

![TLS Error Step 14 of task 3](https://user-images.githubusercontent.com/51210674/92291430-76610e80-eecd-11ea-9e66-3e0d56491fbd.png)

**Comment by DawnmarieDesJardins** [comment]
@kevlopez69 
Thanks Kevin!  Our author did some pre-issue investigation.  While we work on a fix, can you try this and let us know?

As a workaround, Kevin can downgrade the minimum TLS version in his storage account configuration.  We will need to work out the version used by MS SQL and add the downgrade step to the lab.
I’ve not reproduced the issue or verified the workaround, but it seems very plausible. It would be good to hear from the Kevin if this fixes the issue.

**Comment by kevlopez69** [comment]
Thank you. The fix worked for the TLS, I downgraded as was able to proceed. The challenge now is one I faced before as well, on step 34 of task 3 when trying to logon to SQLVM2 I receive the attached error. I tried adding the logons a few times, and ensured the passwords were set, almost feels like it happens immediately, like it’s not even making it to SQLVM2. Your assistance is appreciated.

**Comment by SimonOpsgilityNeale** [comment]
@DawnmarieDesJardins A couple of requests here.  @jtuliani as for this to be broken up into two issues.  Issue 1 would be related to the following "As a workaround, Kevin can downgrade the minimum TLS version in his storage account configuration. We will need to work out the version used by MS SQL and add the downgrade step to the lab." as we will need to update the lab.

**Comment by SimonOpsgilityNeale** [comment]
@DawnmarieDesJardins Issue 2 would be for the following "Thank you. The fix worked for the TLS, I downgraded as was able to proceed. The challenge now is one I faced before as well, on step 34 of task 3 when trying to logon to SQLVM2 I receive the attached error. I tried adding the logons a few times, and ensured the passwords were set, almost feels like it happens immediately, like it’s not even making it to SQLVM2. Your assistance is appreciated." @jtuliani requested the attached error as it does not seem to be attached

**Comment by kevlopez69** [comment]
Pics of the errors. I have since deleted all RG’s and resources as they ate up my credit $$.

**Comment by DawnmarieDesJardins** [comment]
@kevlopez69 
Hi Kevin.
Our author didn't get an error when working through the exercise so, without your screenshot, I'm afraid we can't help.  I'm going to close this issue.  When you get a chance to run the workshop again, if you can't get past this step, please resubmit with screenshots so we can investigate.  Thank you!

**Comment by kevlopez69** [comment]
Got it, I did submit the pics, they are attached again here.

**Comment by DawnmarieDesJardins** [comment]
@kevlopez69 
There's no attachment to the conversation box above....is it the same shot as the very first comment on 9/4?
![Screenshot 2020-09-10 141440](https://user-images.githubusercontent.com/39317565/92807773-07bdfe00-f370-11ea-97a4-15f84d4c69f0.png)

**Comment by kevlopez69** [comment]
Trying it again, it shows below.

**Comment by kevlopez69** [comment]
[cid:image002.png@01D6877E.4C265D20]

From: Kevin Lopez
Sent: Thursday, September 10, 2020 2:20 PM
To: microsoft/MCW-Building-a-resilient-IaaS-architecture <reply@reply.github.com>; microsoft/MCW-Building-a-resilient-IaaS-architecture <MCW-Building-a-resilient-IaaS-architecture@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [microsoft/MCW-Building-a-resilient-IaaS-architecture] Issue on Step 14 of task 3 (#53)

Trying it again, it shows below.

**Comment by DawnmarieDesJardins** [comment]
@kevlopez69 
No image still, sorry.  Can you save a .png snip on your desktop and then drag it into the issue text box?

**Comment by kevlopez69** [comment]
![image](https://user-images.githubusercontent.com/51210674/92811953-ca5b6f80-f373-11ea-92d0-2e0c63179042.png)

**Comment by DawnmarieDesJardins** [comment]
@kevlopez69 - Got it, thank you!
@jtuliani @SimonOpsgilityNeale - Jonathan, please review and advise.

**Comment by jtuliani** [comment]
I'm going to submit a fix in a moment for the TLS issue. The fix will downgrade the minimum TLS version for the cloudwitness storage account as part of the account create wizard.

The other issue you mentioned was authenticating to SQLVM2 at step 34 of task 3. I've just been though it, and it worked perfectly, so there isn't more I can do here:
![image](https://user-images.githubusercontent.com/8792554/93234275-ff9cfe80-f773-11ea-8146-9e2ed55056e0.png)
