### ISSUE TITLE
Exercise2/Task3/Broken graphic

### ISSUE THREAD

**Issue by deltadan** [microsoft/MCW-Building-a-resilient-IaaS-architecture#55]
https://github.com/microsoft/MCW-Building-a-resilient-IaaS-architecture/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Building%20a%20resilient%20IaaS%20architecture.md#task-3-configure-dr-for-the-sql-server-tier

Broken Link:

https://github.com/microsoft/MCW-Building-a-resilient-IaaS-architecture/blob/master/Hands-on%20lab/images/ha-lb.png

**Comment by DawnmarieDesJardins** [comment]
@jtuliani - Hi Jonathan.  Please review and advise/fix.  GitHub isn't allowing me to assign the issue to you at this time.
