### ISSUE TITLE
NAT Gateway issues

### ISSUE THREAD

**Issue by deltadan** [microsoft/MCW-Building-a-resilient-IaaS-architecture#57]
In order to get deployments to work properly with this lab, I had to add all of the subnets to the NAT gateway. 

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"DeploymentFailed\",\r\n \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\",\r\n \"details\": [\r\n {\r\n \"code\": \"Conflict\",\r\n \"message\": \"{\\r\\n \\\"status\\\": \\\"Failed\\\",\\r\\n \\\"error\\\": {\\r\\n \\\"code\\\": \\\"ResourceDeploymentFailure\\\",\\r\\n \\\"message\\\": \\\"The resource operation completed with terminal provisioning state 'Failed'.\\\",\\r\\n \\\"details\\\": [\\r\\n {\\r\\n \\\"code\\\": \\\"VMExtensionProvisioningError\\\",\\r\\n \\\"message\\\": \\\"VM has reported a failure when processing extension 'InstallAD'. Error message: \\\\\\\"Failed to download all specified files. Exiting. Error Message: The remote name could not be resolved: 'cloudworkshop.blob.core.windows.net'\\\\\\\"\\\\r\\\\n\\\\r\\\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot \\\"\\r\\n }\\r\\n ]\\r\\n }\\r\\n}\"\r\n }\r\n ]\r\n }\r\n ]\r\n }\r\n}"},{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"DeploymentFailed\",\r\n \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\",\r\n \"details\": [\r\n {\r\n \"code\": \"Conflict\",\r\n \"message\": \"{\\r\\n \\\"status\\\": \\\"Failed\\\",\\r\\n \\\"error\\\": {\\r\\n \\\"code\\\": \\\"ResourceDeploymentFailure\\\",\\r\\n \\\"message\\\": \\\"The resource operation completed with terminal provisioning state 'Failed'.\\\",\\r\\n \\\"details\\\": [\\r\\n {\\r\\n \\\"code\\\": \\\"VMExtensionProvisioningError\\\",\\r\\n \\\"message\\\": \\\"VM has reported a failure when processing extension 'InstallWebApp'. Error message: \\\\\\\"Failed to download all specified files. Exiting. Error Message: The remote name could not be resolved: 'cloudworkshop.blob.core.windows.net'\\\\\\\"\\\\r\\\\n\\\\r\\\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot \\\"\\r\\n }\\r\\n ]\\r\\n }\\r\\n}\"\r\n }\r\n ]\r\n }\r\n ]\r\n }\r\n}"},{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"DeploymentFailed\",\r\n \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\",\r\n \"details\": [\r\n {\r\n \"code\": \"Conflict\",\r\n \"message\": \"{\\r\\n \\\"status\\\": \\\"Failed\\\",\\r\\n \\\"error\\\": {\\r\\n \\\"code\\\": \\\"ResourceDeploymentFailure\\\",\\r\\n \\\"message\\\": \\\"The resource operation completed with terminal provisioning state 'Failed'.\\\",\\r\\n \\\"details\\\": [\\r\\n {\\r\\n \\\"code\\\": \\\"VMExtensionProvisioningError\\\",\\r\\n \\\"message\\\": \\\"VM has reported a failure when processing extension 'InstallDB'. Error message: \\\\\\\"Failed to download all specified files. Exiting. Error Message: The remote name could not be resolved: 'cloudworkshop.blob.core.windows.net'\\\\\\\"\\\\r\\\\n\\\\r\\\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot \\\"\\r\\n }\\r\\n ]\\r\\n }\\r\\n}\"\r\n }\r\n ]\r\n }\r\n ]\r\n }\r\n}"}]}

Many students got a failure that the script extensions didn't deploy properly. The steps I used to resolve the problem was as followed:

Navigate to your VNet1Nat and under Subnets enable all subnets

On ADVM2, WEBVM2, SQLVM2 under the uninstall the extension

Rerun the deployment

I had them confirm their deployments, but using AD users and computers on ADVM1 to make sure all VMs were added to the domain.

**Comment by deltadan** [comment]
I thought about this one a little more today - I think that the initial VMs were off when did this deployment which would explain this issue. If the new VMs were pointed at the DNS server ADVM1 as the default DNS server for the VNET and it was off that would explain them not being able to see the URL to the storage account. So that might have been the issue, so that dependency should maybe be called out in the docs?

Another thought - I was trying to debug which scripts and paths they were calling and they are being called from a storage account? That seems strange to call a script from GitHub to a storage account? why not just call them from the repo? You can't read the index of the storage account but you could load a public repo....just a thought.

**Comment by dwnatwick** [comment]
@deltadan, please provide the Exercise, Task, and step number(s) that you are referring to here.  It is hard to determine where the issue due to the size of the lab guide and number of steps.  Thank you very much.

**Comment by DawnmarieDesJardins** [comment]
@deltadan 
Hi Dan.  Based on your feedback, we've scheduled a full test/fix for this workshop.  In the next few weeks, @dwnatwick will review the entire workshop and update as necessary.  Please keep an eye out for a reviewed version mid-December.

We appreciate your bringing these to our attention!

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #69
