### ISSUE TITLE
Wrong user name in picture

### ISSUE THREAD

**Issue by deltadan** [microsoft/MCW-Building-a-resilient-IaaS-architecture#58]
This picture shows mcwadmin as the user name and the lab uses contoso\demouser for the creds

https://cloudworkshop.blob.core.windows.net/building-resilient-iaas-architecture/Hands-on%20lab/images/image173.png

**Comment by dwnatwick** [comment]
This field is grayed out in the screenshot as an auto-populated field.  There is more than one screenshot like this for each of the SQL servers.  I will comment for each of these screenshots that the username that will appear in your lab should be contoso\demouser.
