### ISSUE TITLE
Exercise 1/Task3/2 - confusing

### ISSUE THREAD

**Issue by deltadan** [microsoft/MCW-Building-a-resilient-IaaS-architecture#60]
The instructions tell the user to click "Review+Create" and then on the next step tells them to switch to advanced. About half of my students clicked to create prior to seeing the next steps. Would be better to have the TLS step-change prior to clicking "Review+Create"Review+Create.

**Comment by dwnatwick** [comment]
Updated screenshot to resolve the issue.  Added numbered steps to make this less confusing.  Removed the highlight/call-out of Review+Create in the Basics tab.
