### ISSUE TITLE
Exercise1/Task4/Number2 - bad path

### ISSUE THREAD

**Issue by deltadan** [microsoft/MCW-Building-a-resilient-IaaS-architecture#61]
The instruction says: In WebVM1, open Windows Explorer, navigate to C:* and open the Web.config** file using Notepad.

should be: c:\inetpub\wwwroot\web.config

**Comment by deltadan** [comment]
Should also add a step to have them start-->run-->iisreset /restart from the command line of the web.config change isn't running.

**Comment by dwnatwick** [comment]
Updated in November 3, 2020 pull request
