### ISSUE TITLE
SQL AOG connection to BCDRAOG is not working

### ISSUE THREAD

**Issue by deltadan** [microsoft/MCW-Building-a-resilient-IaaS-architecture#62]
There is a step to check for BCDRAOG from SQL Management Studio that doesn't work. There is a DNS name for it and can ping bcdraog.contoso.com with a return of 10.0.2.100, but can't load it from management studio. This caused me to have to use 10.0.2.100 in the web.config file.

**Comment by dwnatwick** [comment]
@deltadan.  Can you let me know which Exercise, Task, and step you are mentioning here.  I have had no issues with configuring BCDRAOG within SQL Management Studio today following the steps in the lab.  I have made some adjustments to some screenshots along the way that may make some of these steps more clear, however.

**Comment by DawnmarieDesJardins** [comment]
@deltadan 
Hi Dan.  Based on your feedback, we've scheduled a full test/fix for this workshop.  In the next few weeks, @dwnatwick will review the entire workshop and update as necessary.  Please keep an eye out for a reviewed version mid-December.

We appreciate your bringing these to our attention!

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR  #69
