### ISSUE TITLE
Random SQL Servers can't login with contoso\demouser

### ISSUE THREAD

**Issue by deltadan** [microsoft/MCW-Building-a-resilient-IaaS-architecture#63]
Some students had issues with contoso\demouser working as logon to SQL after changing the service account and restarting in SQL config manager.  I tried to troubleshoot but was unable to determine what the issue was.

**Comment by dwnatwick** [comment]
Working on this.  Will need to run through the lab and see if the issue will re-create itself.  Since it was only some students, it seems like a system or user error, but we will check it out.

**Comment by deltadan** [comment]
I'm also running this lab again with students, so will be on the lookout again for it.

**Comment by dwnatwick** [comment]
Thank you, Dan.  Please let me know if it re-creates itself and if there is anything in common with the issue taking place (like a particular region, for example).  Thank you.

**Comment by dwnatwick** [comment]
@deltadan, I ran this lab today and had no issue with connecting to the SQL servers after Config manager restart.  Must be an intermittent problem or perhaps a mistake in password entry.

**Comment by deltadan** [comment]
I had a customer with the issue again today. error code 18456 - never could get connected to the SQL server.  had to rebuild the box.

**Comment by dwnatwick** [comment]
@deltadan, Since this is seems to be happening to intermittent users, it does not appear to be an issue with the lab or the deployment code, but more of a glitch in the system.  Especially if rebuilding/redeploying the code resolves the issue.  If there is something specific that you see in the code to change and fix the issue, let me know.  If we are only seeing it a small percentage of the time, I think that we should close and then just track if this issue continues to happen.  Thank you very much.

**Comment by deltadan** [comment]
It's happened every time I've used this course? So about 30% failure. I would think about running the lab a few more times to see if you can get it to happen and troubleshoot.

**Comment by dwnatwick** [comment]
Thank you for the feedback @deltadan.  What specific exercise/task are you seeing this failure appear?

**Comment by deltadan** [comment]
Yesterday we saw it with a student right after he ran the second deployment. It was on SQLVM2. So, I started having the students just run the templates and then basition/rdp into all servers and with the SQL server have them open SMSS and connect. Just can't connect and get that error? Since there is not local creds you can't login to the SQL server to try and troubleshoot the issue.

**Comment by dwnatwick** [comment]
Thanks, @deltadan.  We will try to recreate and troubleshoot more to see if it can be re-created.  Will keep this open for now. Thank you.

**Comment by DawnmarieDesJardins** [comment]
@deltadan 
Hi Dan.  Based on your feedback, we've scheduled a full test/fix for this workshop.  In the next few weeks, @dwnatwick will review the entire workshop and update as necessary.  Please keep an eye out for a reviewed version mid-December.

We appreciate your bringing these to our attention!

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #69
