### ISSUE TITLE
Is the headquarters in Miami or Wyoming?

### ISSUE THREAD

**Issue by iamalexmang** [microsoft/MCW-Building-a-resilient-IaaS-architecture#71]
The WDS guide reads: '_Contoso Insurance (CI), headquartered in Miami, provides insurance solutions [...]_'. And then, in the same paragraph: '_The company's headquarters in in Cheyenne, Wyoming with a second large location in Seattle, Washington along with three smaller branch offices scatted around the United States._'.
Not at all helpful when it comes to picking the designated regions for resiliency...

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #72
