### ISSUE TITLE
Issues in the lab

### ISSUE THREAD

**Issue by Divyasri199** [microsoft/MCW-Building-a-resilient-IaaS-architecture#75]
Issue 1 : 
 In [Exercise-1/ Task-3/ Step-6](https://github.com/microsoft/MCW-Building-a-resilient-IaaS-architecture/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Building%20a%20resilient%20IaaS%20architecture.md), Screenshot and instruction needs to be replaced.

In the BackendPool1 blade, select + Add and choose the two SQL VMs then click on Add from Add virtual machines to backend pool.

![image](https://user-images.githubusercontent.com/83349577/136410623-1272f2b3-7fde-416f-a317-f0ce9f8a65ec.png)

After adding You can see the SQL vms on “Backendpool1” page. Now click on save.

![image](https://user-images.githubusercontent.com/83349577/136410790-a1b13e10-b36f-4eae-acc0-3ac7e1ca34c2.png)

Issue 2: 

In [Exercise-2/ Task-3/ Step-1 ](https://github.com/microsoft/MCW-Building-a-resilient-IaaS-architecture/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Building%20a%20resilient%20IaaS%20architecture.md), Screenshot and instruction need to be updated.

1. Click on  +Add

![image](https://user-images.githubusercontent.com/83349577/136411340-843f62c0-8e44-4ef4-adc1-3560fd34bcd4.png)

2. Select sqlvm3 and click on Add

![image](https://user-images.githubusercontent.com/83349577/136411494-b3dd7ab1-1984-4291-85b0-77819f999811.png)

3.  And click on Save under the Backendpool1 page.

Issue 3: 

In [Exercise-2/ Task-4/ Step-7  ](https://github.com/microsoft/MCW-Building-a-resilient-IaaS-architecture/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Building%20a%20resilient%20IaaS%20architecture.md), the Screenshot needs to be updated with the below-mentioned screenshot.

![image](https://user-images.githubusercontent.com/83349577/136411877-4f9b81f8-cd77-4cc5-b373-082d23d92053.png)

Issue 4:

In [Exercise-2/ Task-4/ Step-10  ](https://github.com/microsoft/MCW-Building-a-resilient-IaaS-architecture/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Building%20a%20resilient%20IaaS%20architecture.md), Mentioned to proceed but need to wait for till replication is done.

Issue 5:

In [Exercise-2/ Task-4/ Step-13  ](https://github.com/microsoft/MCW-Building-a-resilient-IaaS-architecture/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Building%20a%20resilient%20IaaS%20architecture.md), Screenshot need to be updated

![image](https://user-images.githubusercontent.com/83349577/136412350-de230792-c820-48a1-88c6-f0d2d3539f81.png)

Issue 6: 

In [Exercise-2/ Task-4/ Step-20   ](https://github.com/microsoft/MCW-Building-a-resilient-IaaS-architecture/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Building%20a%20resilient%20IaaS%20architecture.md), 

In the Microsoft guide, it is mentioned to select  Run Book name as ASRRunBookWEB, but it is not available in the portal.

As ASRRunBookWEB is not available in the portal, selected ASRWEBFailover.

Issue 7:

In [Exercise-2/ Task-4/ Step-20   ](https://github.com/microsoft/MCW-Building-a-resilient-IaaS-architecture/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Building%20a%20resilient%20IaaS%20architecture.md), 

OK button is not working in step-20. 
Work Around: Ok button works when you click on OK button and close the page. Changes will reflect in the further steps.

![image](https://user-images.githubusercontent.com/83349577/136412876-45953939-df68-4590-b70b-ea6c9c5ca6d9.png)

Issue 8:

In [Exercise-2/ Task-5/ Step-10   ](https://github.com/microsoft/MCW-Building-a-resilient-IaaS-architecture/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Building%20a%20resilient%20IaaS%20architecture.md), was not able to access the web page even after waiting for 30 min. 

Issue 9:

In [Exercise-4/ Task-2/ Step-1    ](https://github.com/microsoft/MCW-Building-a-resilient-IaaS-architecture/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Building%20a%20resilient%20IaaS%20architecture.md), web page is not available

Showing error as 
Our services aren't available right now We're working to restore all services as soon as possible. Please check back soon.00sldYQAAAADE7qwMqYSVQowW1IliqUHDQ0hHRURHRTE2MjAARWRnZQ==

Issue 10:

In [Exercise-4/ Task-3/ Step-4    ](https://github.com/microsoft/MCW-Building-a-resilient-IaaS-architecture/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Building%20a%20resilient%20IaaS%20architecture.md), the web page not working with the IP of front door application.

Showing error as:
Our services aren't available right now,  We're working to restore all services as soon as possible. Please check back soon. 00sldYQAAAADE7qwMqYSVQowW1IliqUHDQ0hHRURHRTE2MjAARWRnZQ==

**Comment by DawnmarieDesJardins** [comment]
Last two points address in merge of PR #78.  Closing issue as resolved.
