### ISSUE TITLE
Azure Pass - VM Provisioning Error

### ISSUE THREAD

**Issue by rodkr** [microsoft/MCW-Building-a-resilient-IaaS-architecture#79]
Provisioning VM's fail when using a Microsoft provided Azure Pass.   VM size not available; suggests D5 family usage instead.  Would like to see VM templates updated to modern Compute Family.  Planning to use this lab, tomorrow Dec 14 in Mountain Time.

**Comment by rodkr** [comment]
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"InvalidTemplateDeployment","message":"The template deployment failed with error: 'The resource with id: '/subscriptions/c6dfae48-a06c-4e10-a7c3-3ed46d49a5be/resourceGroups/ContosoRG1/providers/Microsoft.Compute/virtualMachines/ADVM1' failed validation with message: 'The requested size for resource '/subscriptions/c6dfae48-a06c-4e10-a7c3-3ed46d49a5be/resourceGroups/ContosoRG1/providers/Microsoft.Compute/virtualMachines/ADVM1' is currently not available in location 'centralus' zones '1' for subscription 'c6dfae48-a06c-4e10-a7c3-3ed46d49a5be'. Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details.'.'."}]}

**Comment by rodkr** [comment]
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "InvalidTemplateDeployment",
      "message": "The template deployment failed with error: 'The resource with id: '/subscriptions/c6dfae48-a06c-4e10-a7c3-3ed46d49a5be/resourceGroups/ContosoRG1/providers/Microsoft.Compute/virtualMachines/ADVM1' failed validation with message: 'The requested size for resource '/subscriptions/c6dfae48-a06c-4e10-a7c3-3ed46d49a5be/resourceGroups/ContosoRG1/providers/Microsoft.Compute/virtualMachines/ADVM1' is currently not available in location 'centralus' zones '1' for subscription 'c6dfae48-a06c-4e10-a7c3-3ed46d49a5be'. Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details.'.'."
    }
  ]
}

**Comment by DawnmarieDesJardins** [comment]
@KitSkin - Hi Kit.  Please review and advise.  This is the issue for the email I sent to you Friday afternoon.  Rod has a scheduled presentation tomorrow.

**Comment by rodkr** [comment]
Thank you Dawn Marie.

@KitSkin If you have a @microsoft.com alias; I may give you permission to the Azure Pass subscription for testing.  I'm also available today for testing too.

Thank you in advance!

Rod

**Comment by KitSkin** [comment]
Hi Rod,

I work for Opsgility, a Microsoft training partner, so I don’t have an @microsoft.com login.  If you allow access to external, I do have an Azure AD of ***@***.******@***.***> if you would like to grant access, but based on your details, I think can work on reproducing it and resolving the issue.

Thank you,
-Kit

**Comment by rodkr** [comment]
Hi Kit,

Sounds good - let me know - I can add your AAD account as a contributor to that subscription for a test.

R

**Comment by KitSkin** [comment]
> Hi Kit, Sounds good - let me know - I can add your AAD account as a contributor to that subscription for a test. R 

Use kskinner <at> opsgility <dot> com for my AAD.

**Comment by DawnmarieDesJardins** [comment]
@rodkr - PR fix to the lab has been merged.  Closing issue as resolved.
