### ISSUE TITLE
LabRG Deployment Failure for Extensions of LabVM - West US2

### ISSUE THREAD

**Issue by rodkr** [microsoft/MCW-Building-a-resilient-IaaS-architecture#81]
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "VMExtensionProvisioningError",
      "message": "VM has reported a failure when processing extension 'CustomScriptExtension1'. Error message: \"Finished executing command\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot "
    }
  ]
}

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #83

**Comment by rodkr** [comment]
Attempted this provision again using Azure Pass; error continues:
{
    "status": "Failed",
    "error": {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'CustomScriptExtension1'. Error message: \"Finished executing command\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot "
    }
}
