### ISSUE TITLE
ContosoRG1 SQLVW Deployment Failure - M has reported a failure when processing extension 'InstallDB'. Error message: \\\"Failed to download all specified files. Exiting. Error Message: The request was aborted: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by rodkr** [microsoft/MCW-Building-a-resilient-IaaS-architecture#82]
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
            {
                "code": "Conflict",
                "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'InstallDB'. Error message: \\\"Failed to download all specified files. Exiting. Error Message: The request was aborted: Could not create SSL/TLS secure channel.\\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot \"\r\n      }\r\n    ]\r\n  }\r\n}"
            }
        ]
    }
}

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #83

**Comment by rodkr** [comment]
InstallDB extension continues to fail - Provisioning on Azure Pass Subscription.

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'InstallDB'. Error message: \"Finished executing command\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot "}]}
