### ISSUE TITLE
SQLVM2 Fails to deploy SQLVM-Wrapper

### ISSUE THREAD

**Issue by rodkr** [microsoft/MCW-Building-a-resilient-IaaS-architecture#87]
Deployed as size: Standard D2s v3 (2 vcpus, 8 GiB memory)
---------------------------

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'InstallDB'. Error message: \"Command execution finished, but failed because it returned a non-zero exit code of: '1'. The command had an error output of: 'C:\\Packages\\Plugins\\Microsoft.Compute.CustomScriptExtension\\1.10.12\\Downloads\\0\r\n\\deploy-sqlvm-wrapper.ps1 : Missing an argument for parameter 'dbsource'. \r\nSpecify a parameter of type 'System.Object' and try again.\r\n + CategoryInfo : InvalidAr...' For more information, check the instance view by executing Get-AzVmssVm or Get-AzVm (https://aka.ms/GetAzVm). These commands can be executed using CloudShell (https://aka.ms/CloudShell)\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot "}]}

**Comment by texnomore** [comment]
I will have Kit look into this asap. 😊

Adrianne Agee
Project Manager
Opsgility
(832) 364-7001
***@***.******@***.***>
***@***.***>[Logo  Description automatically generated]

**Comment by DawnmarieDesJardins** [comment]
@rodkr @KitSkin 
Hi gentlemen.  I see you have an email conversation regarding this issue.  Rod, you needed to choose D2s_v5 size and have requested that.  Can we close this issue?

**Comment by rodkr** [comment]
I'm awaiting a quota increase to verify that the build works on the Azure Pass correctly with the v5 size.

R

**Comment by rodkr** [comment]
I've confirmed the same SQL DB Install issue on another subscriptions.  V5 VM chosen.

R

Sent from Outlook<http://aka.ms/weboutlook>

**Comment by rodkr** [comment]
This happens for both SQLVM1 and SQLVM2
