### ISSUE TITLE
Issue in Exercise 2 Task 3

### ISSUE THREAD

**Issue by kaminiwalunj** [microsoft/MCW-Building-a-resilient-IaaS-architecture#90]
In Exercise 2 Task 3 Step 20, while connecting to SQLVM3 getting below mentioned error. 
The connectivity to SQLVM3 is failing. 

![image](https://user-images.githubusercontent.com/88807671/148392362-db480e4b-cb99-48a8-8737-cb95dc8a9281.png)

**Comment by sumitmalik51** [comment]
Hi @DawnmarieDesJardins , do we have any updates here? We have a lab scheduled for 14th Jan for this lab..

Thanks

**Comment by DawnmarieDesJardins** [comment]
@KitSkin - Hi Kit.  Please review and advise.  We have a presentation this week.

**Comment by KitSkin** [comment]
Hi @sumitmalik51 , I've been attempting to duplicate it, but making sure the two deployments of the [Before lab](https://github.com/microsoft/MCW-Building-a-resilient-IaaS-architecture/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Building%20a%20resilient%20IaaS%20architecture.md) steps and the Exercise 1/Task 1 deployment and the command deployment in Exercise 2/Task 1. 

Some things to try troubleshooting:

- Attempt to RDP to SQLVM3 as demouser@contoso.com
- Verify the SQL services are running on SQLVM3
- Click the "Show details" to see if there are any additional details on it
- Double check there are not errors in any deployments of the ContosoRG1/RG2

**Comment by sumitmalik51** [comment]
Hi @KitSkin , we were able to resolve this issue and we are good to close this. Thanks
