### ISSUE TITLE
Resource: LabVM/CustomScriptExtension1 / Status: Conflict

### ISSUE THREAD

**Issue by fyunis** [microsoft/MCW-Building-a-resilient-IaaS-architecture#92]
Hello i'm trying to execute the workshop, but the following error shows while executing the Taks 1 of the before of HOL guide:

  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "VMExtensionProvisioningError",
      "message": "VM has reported a failure when processing extension 'CustomScriptExtension1'. Error message: \"Finished executing command\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot "
    }
  ]
}

In extension section of the VM, the following shows:

[
    {
        "code": "ComponentStatus/StdOut/succeeded",
        "level": "Info",
        "displayStatus": "Provisioning succeeded",
        "message": "Windows PowerShell \r\nCopyright (C) Microsoft Corporation. All rights reserved.\r\n\r\n"
    },
    {
        "code": "ComponentStatus/StdErr/succeeded",
        "level": "Info",
        "displayStatus": "Provisioning succeeded",
        "message": "Processing -File 'https://raw.githubusercontent.com/microsoft/MCW-Building-a-resilient-IaaS-architecture/master/Hands-on%20lab/Resources/scripts//configure-labvm.ps1' failed: The given path's format is not supported. Specify a valid path for the -File parameter.\r\n"
    }
]

Please your support

**Comment by KitSkin** [comment]
The template had a calculated script path value with an extra 'slash'.  That has been removed to repair the template.  Redeploying the Lab VM will work correctly now.

**Comment by fyunis** [comment]
Hello, 
Thanks for the support, LabVM could be deployed without problems, as well as all the templates and scripts of the workshop.

There is only a problem in the availability tests with the database service, when trying to execute the automatic failover (turning off SQLVM1), it does not proceed, and the cluster goes down; if SQLVM1 goes online, everything is working properly again.

The error's that show are the following:
The role of this availability replica is unhealthy. The replica does not have either the primary or secondary role.
The availability group is not ready for automatic failover. The primary replica and a secondary replica are configured for automatic failover, however, the secondary replica is not ready for an automatic failover. Possibly the secondary replica is unavailable

I have been reviewing the problem, but the procedures indicated on the web, do not provide a solution.
Links reviwed:
https://docs.microsoft.com/en-us/archive/blogs/sqlserverfaq/inf-alwayson-the-secondary-database-doesnt-come-automatically-when-the-primary-instance-of-sql-server-goes-down
https://docs.microsoft.com/en-us/archive/blogs/sqlserverfaq/inf-alwayson-the-secondary-database-doesnt-come-automatically-when-the-primary-instance-of-sql-server-goes-down

Please let me know if i need to poste this issue in another thread.

Please your support!

Thanks!

**Comment by DawnmarieDesJardins** [comment]
@texnomore @KitSkin - Any update for us?  Thank you.

**Comment by fyunis** [comment]
hello,
hope all doing great! 
any update on the issue?

For the other hand, i have a question:

1. Exist any azure limitation deploying this workshops with Azure Pass? because i was teaching this workshop and when the students start deploying the task 2 of before HOL guide, the deployment show an error that indicate the size of the VM is not available for the region. This error is showing with all the types of VM that they can choose.

And when i deploying the lab using my subscription the same task pass successfully.

Stay tuned.

Thanks

**Comment by DawnmarieDesJardins** [comment]
@KitSkin @texnomore 
Hello.  Please provide an update to this issue.

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #94
