### ISSUE TITLE
BHOL : Resources SQLVM1 and WebVM1 fail on creation

### ISSUE THREAD

**Issue by msftnadavbh** [microsoft/MCW-Building-a-resilient-IaaS-architecture#93]
Same error for both VMs using the template in BHOL : 

{
    "status": "Failed",
    "error": {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'JoinDomain'. Error message: \"Exception(s) occured while joining Domain 'contoso.com'\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/vmextensionwindowstroubleshoot "
    }
}

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'JoinDomain'. Error message: \"Exception(s) occured while joining Domain 'contoso.com'\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/vmextensionwindowstroubleshoot "}]}

Both fail on domain join.
Unable to proceed because of this

**Comment by fyunis** [comment]
Hello!
Hope all doing great!
Any update of this issue?

**Comment by fyunis** [comment]
Hi @msftnadavbh , are you using a different password? if so, this is the reason for the error. 
Use the key indicated in the guide

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #94
