### ISSUE TITLE
BHOL Task 3, Step 4 failing

### ISSUE THREAD

**Issue by sadukie** [microsoft/MCW-Building-a-resilient-IaaS-architecture#98]
The ARM templates show successful deployments, but the seeded data isn't loading.

The policy data isn't loading like it should. We get an error page when trying to pull up the Current Policy Offerings.

**Comment by sadukie** [comment]
@DawnmarieDesJardins @timahenning Heads up that once I connected the PowerShell script in #97 , we found that the data isn't loading like it should. I'm tracking this down further. Logging this issue so we're all aware that I know about this.

**Comment by sadukie** [comment]
Further debugging has led to this error in the `deploy-sqlvm-wrapper-log` file on SQLVM1:

```
Set up data, backup and log directories in SQL, plus mixed-mode auth
Instance Name: Localhost
Login Mode:
Exception setting "LoginMode": "Failed to connect to server Localhost."
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
    + PSComputerName        : SQLVM1
```

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #99
